import Head from 'next/head';

import HomePage from '@/src/components/home/home-page';

export default function Home({ data }) {
    return (
        <>
            <Head>
                <title>Events App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <HomePage data={data} />
        </>
    );
}

//we don't need getServerSideProps here cuz we don't need to fetched at request time but for the learning purpose we do use it anyway. who cares?! lol...

export async function getServerSideProps() {
    const { events_categories } = await import('/data/data.json');

    return {
        props: {
            data: events_categories,
        },
    };
}
