import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '@/styles/Home.module.css';

export default function Home({ data }) {
    return (
        <>
            <Head>
                <title>Events App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <header>
                <nav>
                    <Link href="/">Home</Link>
                    <Link href="/events">Events</Link>
                    <Link href="/about-us">About Us</Link>
                </nav>
            </header>

            <main className={styles.main}>
                {data.map((item) => (
                    <Link href={`/events/${item.id}`} key={item.id} passHref>
                        <Image
                            src={item.image}
                            alt={item.title}
                            width={300}
                            height={300}
                        />
                        <h2>{item.title}</h2>
                        <p>{item.description}</p>
                    </Link>
                ))}
            </main>

            <footer className={styles.footer}>
                <p>
                    &copy; 2023 Code with Sia - A self project for NextJS
                    framework
                </p>
            </footer>
        </>
    );
}

//we don't need getServerSideProps here cuz we don't need to fetched at request time but for the learning purpose we do use it anyway. who cares?! lol...

export async function getServerSideProps() {
    const { events_categories } = await import('/data/data.json');

    return {
        props: {
            data: events_categories,
        },
    };
}
